### ISSUE TITLE
Crawler is failing

### ISSUE THREAD

**Issue by kesara** [ietf-tools/relaton-data-3gpp#17]
Crawler is failing since yesterday.
Logs:
* https://github.com/ietf-tools/relaton-data-3gpp/actions/runs/5390823637/jobs/9786756033#step:7:64
* https://github.com/ietf-tools/relaton-data-3gpp/actions/runs/5402083715/jobs/9812857392#step:7:64
* https://github.com/ietf-tools/relaton-data-3gpp/actions/runs/5407092588/jobs/9824696362#step:7:64

**Comment by strogonoff** [comment]
@andrew2net @CAMOBAP [seems like](https://github.com/ietf-tools/relaton-data-3gpp/actions/runs/5402083715/jobs/9812857392#step:7:60) there is a bug in relaton_3gpp? Or is it a Ruby version mismatch?

**Comment by andrew2net** [comment]
The error occurred because content of remote FTP dir was changed by owner. The last relaton-3gpp update fixed the issue.

**Comment by strogonoff** [comment]
@andrew2net thank you for the update! @stefanomunarini so this is a good example for us of a case where locking dependencies comes back to bite, I guess :)

**Comment by strogonoff** [comment]
Could we determine the minimum version bump that gets us to working relaton-3gpp with fewest or no changes in data rendering? cc @andrew2net @CAMOBAP

**Comment by andrew2net** [comment]
@strogonoff we change minor version in case the data model is changed. As I remember we had a change in content, not the data model, and it caused a problem in ietf-tools. So we decided to lock full version with bug fix number. I'm sure we have bug fixes more often than changing content. So we will have less problem if we allow to update bug fixe versions automatically.

**Comment by kesara** [comment]
What @andrew2net mentioned is the desired outcome here.
It's okay to update versions that are compatible with the BibXML Service.
So if the gems are using semantic versioning, GHA should be only locked info major version changes that break the BibXML service.
GHA should take advantage of any minor, patch updates.

**Comment by kesara** [comment]
The crawler failure is now fixed with the gem version update from https://github.com/ietf-tools/bibxml-service/pull/354

Should we create a new issue to discuss the version locking under BibXML?

**Comment by kesara** [comment]
I've created https://github.com/ietf-tools/bibxml-service/issues/355 to capture version pining improvements.
