### ISSUE TITLE
Interesting field: “radiotechnology”

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-3gpp#2]
Relaton data contains field “radiotechnology” with value “LTE”. It seems very domain-specific and probably outside Relaton model. Should it be parsed as a keyword, perhaps?

**Comment by strogonoff** [comment]
The item in question is https://demo.bibxml.org/api/v1/ref/3gpp/TR_33.879_REL-13_0.1.0/.

**Comment by ronaldtse** [comment]
@strogonoff yes `radiotechnology` is a 3GPP specific thing. It is an attribute in 3GPP deliverables so it is not technically a "keyword", but for indexing/searching purposes parsing it as whatever that works is fine.

**Comment by strogonoff** [comment]
I don’t mind that, but if it is a 3GPP extension we should probably don’t have it under Relaton spec namespace🧐 Rationale in another comment.

**Comment by ronaldtse** [comment]
@strogonoff please file this under relaton-3gpp if there is a continuation. Thanks.

**Comment by strogonoff** [comment]
Covered by https://github.com/relaton/relaton-3gpp/issues/11 now.
