### ISSUE TITLE
Encountered unknown fields: “doctype”, “docstatus”, “editorialgroup”, “release”, “common-ims-spec”

### ISSUE THREAD

**Issue by strogonoff** [ietf-tools/relaton-data-3gpp#5]
Cannot find them in the grammar (https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc).

Field notes:

- It looks like `doctype` might belong somewhere under `docid` field, not sure about the others.
- `editorialgroup` seems like some custom extension outside of Relaton core but relevant for some citations?
- The dash in the following example makes `editorialgroup` contents seem ill-parsed, example:

        "editorialgroup": [
            {
                "name": "C1",
                "type": "prime"
            },
            {
                "name": "-",
                "type": "other"
            },
            {
                "name": "T2",
                "type": "former"
            }
        ],

Example items:

- https://demo.bibxml.org/api/v1/ref/3gpp/TR_33.879_REL-13_0.1.0/
- https://demo.bibxml.org/api/v1/ref/3gpp/TS_29.163_REL-9_9.21.0/
- https://demo.bibxml.org/api/v1/ref/3gpp/TS_27.007_REL-15_15.3.0/ (extended “release” value)

**Comment by ronaldtse** [comment]
This is actually the `meeting` ID from the database, it is not **THE editorial group** itself, but it is editorial group information. It shouldn't be broken down, e.g. "C1-T2" is correct without splitting it.

<img width="170" alt="Screenshot 2021-12-17 at 10 15 40 AM" src="https://user-images.githubusercontent.com/11865/146477824-983d590e-f47f-455e-bf77-f874cbab975e.png">

**Comment by ronaldtse** [comment]
> * It looks like `doctype` might belong somewhere under `docid` field, not sure about the others.

`doctype` exists outside the document identifier. The document identifier may or may not contain a representation of `doctype`.

e.g. "ISO 9001" has `doctype` of `international-standard` but the `docid` only contains `ISO 9001` without mention of the `doctype`.

> * `editorialgroup` seems like some custom extension outside of Relaton core but relevant for some citations?

`editorialgroup` is considered the "author" of the standard. Not all bibliographic data provide this information.

In this case the `meeting` venue and the `rapporteurId` can be considered information about the `editorialgroup`.

**Comment by ronaldtse** [comment]
`release` is the release number of the 3GPP specification. This is specific to 3GPP.

`common-ims-spec` is a boolean attribute of the 3GPP specification, again specific to 3GPP.

**Comment by strogonoff** [comment]
@ronaldtse The explanation helps. However, since they are not in the grammar, the question is again where do I find the spec for those fields.

If we don’t have a shared spec, the UI can’t know how or what to render. This means either the UI will look bad, or it will present incomplete data.

NB specifically regarding org- or doctype-specific fields like `release` or `common-ims-spec` that are not covered by Relaton core spec, it may be a good form to move them under a subkey (e.g., making it `extra.release` or even `extra.3gpp.release`). That would make it clear that semantics of those attributes are not covered by Relaton spec. That would also give the opportunity for that subkey to e.g. specify a schema in future. Otherwise there will be collisions where (1) multiple different documents use the same field with different semantics or (2) Relaton spec wants to start using this field name in the future, but other citations already occupy it.

**Comment by andrew2net** [comment]
> Cannot find them in the grammar (https://github.com/relaton/relaton-models/blob/main/grammars/biblio.rnc).

@strogonoff it's basic grammar. Flavor gems have extensions https://github.com/metanorma/metanorma-model-iso/tree/main/grammars

**Comment by ronaldtse** [comment]
@strogonoff it's a legacy organizational issue... I've posted a task to split them out. (FYI @opoudjis)

**Comment by andrew2net** [comment]
@strogonoff can we close this issue?

**Comment by strogonoff** [comment]
> @strogonoff can we close this issue?

I’ll take note of the fields and close it or transfer it to a more appropriate repository…

**Comment by ronaldtse** [comment]
@strogonoff what's happening with this now?

**Comment by strogonoff** [comment]
Covered by https://github.com/relaton/relaton-3gpp/issues/11 now.
